# Generated by Django 4.1.7 on 2023-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
