# Generated by Django 4.1.7 on 2023-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_remove_commande_statut_commande_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('non paye', 'non payé'), ('payé', 'payé')], max_length=200, null=True),
        ),
    ]
