# Generated by Django 4.1.7 on 2023-02-24 18:29

from django.db import migrations, models
import produit.models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.JSONField(default=1, verbose_name=produit.models.Produit),
            preserve_default=False,
        ),
    ]
