# Generated by Django 4.1.7 on 2023-02-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_alter_commande_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('non payé', 'non payé'), ('payé', 'payé')], max_length=200, null=True),
        ),
    ]
