# Generated by Django 4.1.7 on 2023-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_commande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
