# Generated by Django 4.1.7 on 2023-02-24 19:54

import credit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_credit_date_credit'),
    ]

    #operations = [
        #migrations.AlterField(
            #model_name='credit',
            #name='total',
            #field=models.FloatField(verbose_name=credit.models.Credit.multi_att),
        #),
    #]
