# Generated by Django 4.1.7 on 2023-02-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_credit_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='etat',
        ),
    ]
