# Generated by Django 4.1.7 on 2023-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_remove_credit_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
