# Generated by Django 4.1.7 on 2023-02-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_credit_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_credit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
