# Generated by Django 4.1.7 on 2023-02-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_alter_credit_date_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_credit',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
