# Generated by Django 4.1.7 on 2023-02-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_credit_date_credit_alter_credit_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
