# Generated by Django 4.1.7 on 2023-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_credit_etat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='prix',
            new_name='montant_credit',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='total',
        ),
        migrations.AlterField(
            model_name='credit',
            name='etat',
            field=models.IntegerField(choices=[('non payé', 'non payé'), ('payé', 'payé')]),
        ),
    ]
