# Generated by Django 4.1.7 on 2023-02-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_rename_prix_credit_montant_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='etat',
            field=models.CharField(choices=[('non payé', 'non payé'), ('payé', 'payé')], max_length=200, null=True),
        ),
    ]
